name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Trigger on push to main branch
  pull_request:
    branches:
      - main # Trigger on PR to main branch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: |
          cd api  # Navigate to the API folder where the package.json exists
          npm install

      - name: Run tests
        run: |
          cd api  # Navigate to the API folder where the tests are located
          npm run test -- --testPathPattern=controllers  # Run tests from controllers folder

  docker:
    runs-on: ubuntu-latest
    needs: test # Only run this job if tests pass
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t atishkiran/dwellbase-api .  # Replace with your Docker Hub username and desired repository name

      - name: Push Docker image to Docker Hub
        run: |
          docker push atishkiran/dwellbase-api  # Replace with your Docker Hub username and desired repository name
