name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Trigger on push to the main branch
  pull_request:
    branches:
      - main # Trigger on PR to the main branch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Set to Node.js 18

      - name: Clean npm cache
        run: npm cache clean --force # Clean the npm cache

      - name: Install dependencies
        run: |
          npm install  # Install dependencies from the root package.json

      - name: Run tests
        run: |
          npm run test -- --testPathPattern=api/controllers  # Run tests located in the api/controllers folder

  docker:
    runs-on: ubuntu-latest
    needs: test # Only run this job if tests pass
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t atishkiran/dwellbase-api ./api  # Build Docker image from the api directory

      - name: Push Docker image to Docker Hub
        run: |
          docker push atishkiran/dwellbase-api  # Push Docker image to Docker Hub
